language: java
sudo: required
services:
  - docker

before_install:
  - docker build -t rathna78/docker-springboot-demo2 -f Dockerfile .

script:
  - mvn package -DskipTests

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-springboot-demo2"
  env: "DockerSpringbootDemo2-env"
  bucket_name: "elasticbeanstalk-ap-south-1-863024253731"
  bucket_path: "docker-springboot-demo2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

